# SUBMIT Replication-Controller.yaml
apiVersion: v1
kind: ReplicationController
metadata:
  name: submit-repli-controller
spec:
  replicas: 2
  selector:
    app: submit
  template:
    metadata:
      name: submit
      labels:
        app: submit
    spec:
      containers:
        - name: submit-container
          image: asfiyask/kubernetes-objects:v1.4
          ports:
            - containerPort: 80
