#DEPLOYMENT.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: submit-deployment
  labels:
    app: submit
spec:
  replicas: 3
  selector:
    matchLabels:
      app: submit
  template:
    metadata:
      labels:
        app: submit
    spec:
      containers:
      - name: submit-container
        image: asfiyask/kubernetes-objects:v1.4
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "512Mi" 
            cpu: "0.5"     
          requests:
            memory: "256Mi" 
            cpu: "0.25"    

